### ISSUE TITLE
Broken link to RDA Metadata Principles

### ISSUE THREAD

**Issue by collinschwantes** [rd-alliance/metadata-catalog-v2#12]
The Scope of the Catalog page references the RDA Metadata Principles but the link to that document 
https://www.rd-alliance.org/metadata-principles-and-their-use.html returns a 404 error

**Comment by collinschwantes** [comment]
also happening with https://www.rd-alliance.org/groups/metadata-standards-catalog-working-group.html

**Comment by alex-ball** [comment]
Thanks for reporting. Even organizations with an interest in digital preservation can have a blind spot when it comes to [stopping links from breaking](https://www.w3.org/Provider/Style/URI).

The IG page is an easy fix, but the new home for the Metadata Principles seems a bit harder to track down...

**Comment by alex-ball** [comment]
The page for the Metadata Principles was there, but the file itself seems to have been lost in the transition to the new system. Now fixed.

**Comment by collinschwantes** [comment]
Thanks for fixing that so fast!
